version: '3.8'

services:
  ubuntu22:
    build: .
    container_name: ubuntu22_container
    restart: always
    tty: true
    networks:
      - ubuntu_net
    volumes:
      - ./data:/data
      - ./workspace:/workspace  # Mount the workspace folder
    environment:
      - TZ=UTC
      - API_BASE=http://host.docker.internal:11434
      - MODEL=ollama_chat/llama3
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable communication with the Windows host
    command: /bin/bash -c "source /root/.bashrc && tail -f /dev/null"  # Keep the container running

networks:
  ubuntu_net:
    driver: bridge
